apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi
  template:
    metadata:
      labels:
        app: stedi
    spec:
      containers:
        - name: stedi
          image: gcr.io/cit-262-fall/stedi
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-service
spec:
  selector:
    app: stedi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4567

